### ISSUE TITLE
[Python 2.7] access_points sometimes throws ValueError - missing rssi?

### ISSUE THREAD

**Issue by rfilmyer** [kootenpv/accces_points#1]
I had this running at work, but at a new location I get a `ValueError` if I run the script, either with `access_points` or `access_points -n`. Problematic line seems to be [here](https://github.com/kootenpv/accces_points/blob/master/access_points/__init__.py#L62).

Running OS X Yosemite with Python 2.7.11

```
android-daafae023c116caf:~ roger$ access_points -n
Traceback (most recent call last):
  File "/Users/roger/anaconda/bin/access_points", line 11, in <module>
    sys.exit(main())
  File "/Users/roger/anaconda/lib/python2.7/site-packages/access_points/__init__.py", line 153, in main
    access_points = wifi_scanner.get_access_points()
  File "/Users/roger/anaconda/lib/python2.7/site-packages/access_points/__init__.py", line 33, in get_access_points
    results = self.parse_output(out)
  File "/Users/roger/anaconda/lib/python2.7/site-packages/access_points/__init__.py", line 62, in parse_output
    ap = AccessPoint(ssid, bssid, rssi_to_quality(int(rssi)), security)
ValueError: invalid literal for int() with base 10: ''
```

**Comment by rfilmyer** [comment]
Dump of the `airport -s` command:

```
android-daafae023c116caf:~ roger$ /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -s
                            SSID BSSID             RSSI CHANNEL HT CC SECURITY (auth/unicast/group)
               DIRECT-RL-VIZIOTV 02:6b:9e:84:b5:8c -77  11      Y  -- WPA2(PSK/AES/AES)
      Noisebridge Legacy 2.4 gHz dc:9f:db:1c:b6:81 -45  11      Y  -- NONE
                      ESP_D3B185 1a:fe:34:d3:b1:85 -60  11      N  -- NONE
                           fredo 80:ea:96:f3:7b:fe -76  11      Y  US WPA2(PSK/AES/AES)
                          ATT648 8c:7f:3b:62:bc:10 -76  11      Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP)
             Oh Happy Day Legacy 44:d9:e7:f7:c6:93 -49  11      Y  -- WPA2(PSK/AES/AES)
                          ATT576 64:55:b1:69:76:60 -51  11      Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP)
                          ATT976 38:3b:c8:64:02:5a -67  9       Y  US WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP)
         mesh-admin-mynet-n750-1 06:90:a9:0b:7c:1b -65  6       Y  -- WPA2(PSK/AES/AES)
                      SuperDooby 94:10:3e:81:ec:3a -69  6       Y  -- WPA(PSK/TKIP/TKIP) WPA2(PSK/AES/TKIP)
             Oh Happy Day Legacy 44:d9:e7:f7:c6:60 -89  6       Y  -- WPA2(PSK/AES/AES)
       HP-Print-C1-LaserJet 1102 ec:0e:c4:03:60:c1 -70  6       N  -- NONE
                          ATT784 b8:16:19:7b:66:30 -81  5       N  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP)
                     xfinitywifi 06:f8:93:57:74:00 -79  6       Y  US NONE
                  TP-LINK_5562FC e8:de:27:55:62:fc -86  3,+1    Y  -- WPA2(PSK/AES/AES)
                           BBBBB c2:ff:d4:b3:33:f2 -73  1       Y  -- WPA2(PSK/AES/AES)
                      ESP_0229C3 62:01:94:02:29:c3 -54  1       N  -- NONE
                     xfinitywifi 6e:8f:e0:0f:6e:b0 -71  1       Y  US NONE
                       Canascasa 5c:8f:e0:0f:6e:b0 -74  1       Y  US WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP)
                    CommunityNet 02:27:22:3e:06:55 -43  1       Y  -- NONE
                    Oh Happy Day 46:d9:e7:f8:c6:60 -77  40,-1   Y  -- WPA2(PSK/AES/AES)
                     Noisebridge de:9f:db:1b:b6:81 -47  40,-1   Y  -- NONE
                 peoplesopen.net 02:90:a9:0b:7c:1d -71  157,+1  Y  -- NONE
             Winternet is coming e8:fc:af:fb:44:1a -85  153     Y  US WPA2(PSK/AES/AES)
                 SuperDooby_5GHz 94:10:3e:81:ec:3b -85  149     Y  US WPA(PSK/TKIP/TKIP) WPA2(PSK/AES/TKIP)
                     Noisebridge de:9f:db:1b:6f:b6 -47  48,-1   Y  -- NONE
                    Oh Happy Day 46:d9:e7:f8:c6:93 -74  48,-1   Y  -- WPA2(PSK/AES/AES)

1 IBSS network found:
                            SSID BSSID             RSSI CHANNEL HT CC SECURITY (auth/unicast/group)
          pplsopen.net-node2node ca:fe:c0:de:f0:0d -45  1       Y  -- NONE
```

**Comment by rfilmyer** [comment]
Wait, I got it! I bet the ad hoc network or the newline before that second section is screwing it up!

**Comment by rfilmyer** [comment]
I'm writing a new module that uses the `airport -s -x` option and parsing the XML.

**Comment by kootenpv** [comment]
Not sure why this got closed. Did it get solved by the changes in the PR? I think parsing XML is a lot more sane (if only I had known about that option). Are you still implementing an XML parser? I would for sure accept the PR.

**Comment by rfilmyer** [comment]
So parsing XML is the more sane option by far (especially using the `plistlib` library in the python stdlib). Only issue is that finding out security settings is pretty terrible, but I'm still making decent progress right now.

**Comment by kootenpv** [comment]
@rfilmyer Thanks once more, very happy with the result. I didn't even know about plistlib, it's a nice addition as well.
